# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[λ](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[hostname]
ssh_only = false
format =  "(bold)[$hostname: ](bold fg:cyan)"
trim_at = ".companyname.com"
disabled = false
[username]
style_user = "bold fg:blue"
style_root = "red bold"
format = "(bold )[$user@]($style)"
disabled = false
show_always = true

[directory]
home_symbol = " "
read_only = "  "
style = "bold bg:yellow"
truncation_length = 2
truncation_symbol = "./"
format = '(bold)[$path](fg:yellow)'

